//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacOrderItem
    {
        public int OrderId { get; set; }
        public int VaccinId { get; set; }
        public int Amount { get; set; }
    
        public virtual Vaccin Vaccin { get; set; }
        public virtual VacOrder VacOrder { get; set; }
    }
}
